/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abarrotes.pos.vista;

/**
 *
 * @author danie
 */
public class frmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLogin.class.getName());

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(480, 320);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getRootPane().setDefaultButton(btnIniciarSesion);
        pnlFondo.setBackground(new java.awt.Color(102, 204, 255, 60));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnOlvidasteContraseña = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acceso"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, -1));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 120, -1));

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        btnOlvidasteContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOlvidasteContraseña.setText("¿Olvidaste la contraseña?");
        btnOlvidasteContraseña.setBorderPainted(false);
        btnOlvidasteContraseña.setContentAreaFilled(false);
        btnOlvidasteContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOlvidasteContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOlvidasteContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOlvidasteContraseñaMouseExited(evt);
            }
        });
        btnOlvidasteContraseña.addActionListener(this::btnOlvidasteContraseñaActionPerformed);
        jPanel1.add(btnOlvidasteContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseExited(evt);
            }
        });
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Iniciar Sesión");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pnlFondo.setBackground(new java.awt.Color(121, 121, 121));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 390, 100));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_login1.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 280));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseEntered
        // TODO add your handling code here:
        btnRegistrarse.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    private void btnRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseExited
        // TODO add your handling code here:
        btnRegistrarse.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_btnRegistrarseMouseExited

    private void btnOlvidasteContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOlvidasteContraseñaMouseEntered
        // TODO add your handling code here:
        btnOlvidasteContraseña.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_btnOlvidasteContraseñaMouseEntered

    private void btnOlvidasteContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOlvidasteContraseñaMouseExited
        // TODO add your handling code here:
        btnOlvidasteContraseña.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_btnOlvidasteContraseñaMouseExited

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        // TODO add your handling code here:
        new frmRegistrarse().setVisible(true);
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void btnOlvidasteContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOlvidasteContraseñaMouseClicked
        // TODO add your handling code here:
        new frmOlvidarContraseña().setVisible(true);
    }//GEN-LAST:event_btnOlvidasteContraseñaMouseClicked

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String pass = new String(txtContraseña.getPassword());
        
        if(usuario.isEmpty() || pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Por favor completa todos los campos.");
            return;
        }
        if(usuario.equals("Admin") && pass.equals("1234")) {
            frmVentanaPrincipal menu = new frmVentanaPrincipal();
            menu.setNombreUsuario(usuario);
            menu.setVisible(true);
            this.dispose();
        }else {
            javax.swing.JOptionPane.showMessageDialog(this,"Usuario o Contraseña incorrectos");
            txtContraseña.setText("");
            txtUsuario.setText("");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        frmRegistrarse registro = new frmRegistrarse();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnOlvidasteContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidasteContraseñaActionPerformed
        // TODO add your handling code here:
        frmOlvidarContraseña olvidarContraseña = new frmOlvidarContraseña();
        olvidarContraseña.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOlvidasteContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnOlvidasteContraseña;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}

