/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abarrotes.pos.vista;

/**
 *
 * @author danie
 */
public class frmRegistrarse extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegistrarse.class.getName());

    /**
     * Creates new form frmRegistrarse
     */
    public frmRegistrarse() {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(480, 520);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(btnConfirmar);
        pnlFondo.setBackground(new java.awt.Color(102, 204, 255, 60));
        configurarPermisos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmarContraseña = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        chkPuntoVenta = new javax.swing.JCheckBox();
        chkVentas = new javax.swing.JCheckBox();
        chkProductos = new javax.swing.JCheckBox();
        chkProveedores = new javax.swing.JCheckBox();
        chkInventario = new javax.swing.JCheckBox();
        chkCancelarProducto = new javax.swing.JCheckBox();
        chkCancelarVenta = new javax.swing.JCheckBox();
        txtRegistroDeUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuario\n"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreCompleto.setText("Nombre completo:");
        jPanel1.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreo.setText("Correo electrónico:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        lblConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirmarContraseña.setText("Confirmar Contraseña:");
        jPanel1.add(lblConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));
        jPanel1.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 290, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 280, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        txtContraseña.addActionListener(this::txtContraseñaActionPerformed);
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, -1));
        jPanel1.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        chkPuntoVenta.setText("Punto de venta");
        chkPuntoVenta.setBorder(null);
        chkPuntoVenta.setFocusPainted(false);
        chkPuntoVenta.setRolloverEnabled(false);
        jPanel1.add(chkPuntoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        chkVentas.setText("Módulo ventas");
        chkVentas.setBorder(null);
        chkVentas.setFocusPainted(false);
        chkVentas.setRolloverEnabled(false);
        jPanel1.add(chkVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        chkProductos.setText("Alta de productos");
        chkProductos.setBorder(null);
        chkProductos.setFocusPainted(false);
        chkProductos.setRolloverEnabled(false);
        jPanel1.add(chkProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        chkProveedores.setText("Alta de proveedores");
        chkProveedores.setBorder(null);
        chkProveedores.setFocusPainted(false);
        chkProveedores.setRolloverEnabled(false);
        jPanel1.add(chkProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        chkInventario.setText("Módulo Inventarios");
        chkInventario.setBorder(null);
        chkInventario.setFocusPainted(false);
        chkInventario.setRolloverEnabled(false);
        chkInventario.addActionListener(this::chkInventarioActionPerformed);
        jPanel1.add(chkInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        chkCancelarProducto.setText("Cancelar producto");
        jPanel1.add(chkCancelarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        chkCancelarVenta.setText("Cancelar venta");
        jPanel1.add(chkCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        txtRegistroDeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegistroDeUsuario.setText("Registro de usuario");
        jPanel1.add(txtRegistroDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Permisos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        pnlFondo.setBackground(new java.awt.Color(102, 204, 255));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pnlFondo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel1.add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 160));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_registrarse1.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCompleto.getText();
        String usuario = txtUsuario.getText();
        String correo = txtCorreo.getText();
        String pass1 = new String(txtContraseña.getPassword());
        String pass2 = new String(txtConfirmarContraseña.getPassword());
        
        if(nombre.isEmpty() || usuario.isEmpty() || correo.isEmpty() || pass1.isEmpty() || pass2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        }
        else if(!pass1.equals(pass2)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas deben coincidir");
            txtContraseña.setText("");
            txtConfirmarContraseña.setText("");
        }
        else if(!correo.contains("@") || !correo.contains(".")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un correo electrónico válido.");
            txtCorreo.setText("");
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso.");
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void chkInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkInventarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frmLogin Login = new frmLogin();
        Login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void configurarPermisos() {
        chkInventario.addActionListener(e -> {
            boolean estado = chkInventario.isSelected();
            chkProveedores.setSelected(estado);
            chkProductos.setSelected(estado);
        });
        
        chkVentas.addActionListener(e -> {
            boolean estado = chkVentas.isSelected();
            chkPuntoVenta.setSelected(estado);
            chkCancelarProducto.setSelected(estado);
            chkCancelarVenta.setSelected(estado);
        });

        java.awt.event.ActionListener sincInventario = e -> {
            chkInventario.setSelected(chkProveedores.isSelected() || chkProductos.isSelected());
        };
        java.awt.event.ActionListener sincVentas = e -> {
            chkVentas.setSelected(chkPuntoVenta.isSelected() || chkCancelarProducto.isSelected() || chkCancelarVenta.isSelected());
        };
            
        
        chkProveedores.addActionListener(sincInventario);
        chkProductos.addActionListener(sincInventario);
        chkPuntoVenta.addActionListener(sincVentas);
        chkCancelarProducto.addActionListener(sincVentas);
        chkCancelarVenta.addActionListener(sincVentas);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegistrarse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkCancelarProducto;
    private javax.swing.JCheckBox chkCancelarVenta;
    private javax.swing.JCheckBox chkInventario;
    private javax.swing.JCheckBox chkProductos;
    private javax.swing.JCheckBox chkProveedores;
    private javax.swing.JCheckBox chkPuntoVenta;
    private javax.swing.JCheckBox chkVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblConfirmarContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JLabel txtRegistroDeUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   
}
